#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReleaseReadinessNeed {
    RequiredBeforeFdbProof,
    RequiredBeforeDuckLakeSmoke,
    BenchmarkGatedDeferred,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CatalogOperation {
    CatalogOpen,
    CreateSchema,
    CreateTable,
    AppendDataFiles,
    CurrentTableScan,
    FilePruning,
    TimeTravelScan,
    UpdateOrDelete,
    AlterTable,
    Compaction,
    DataInlining,
    ChangeDataFeed,
    SnapshotMaintenance,
    CleanupFiles,
    ConfigOptions,
    MetadataInspection,
    Migration,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OperationInventory {
    pub operation: CatalogOperation,
    pub typed_call: &'static str,
    pub reads: &'static [&'static str],
    pub writes: &'static [&'static str],
    pub indexes: &'static [&'static str],
    pub transaction_boundary: &'static str,
    pub expected_row_counts: &'static str,
    pub maximum_mutation_size: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RiskInventory {
    pub name: &'static str,
    pub mitigation: &'static str,
    pub need: ReleaseReadinessNeed,
    pub fixture_owner: &'static str,
}

#[must_use]
pub const fn operation_inventory() -> &'static [OperationInventory] {
    &[
        OperationInventory {
            operation: CatalogOperation::CatalogOpen,
            typed_call: "load_latest_snapshot + load_catalog_snapshot",
            reads: &[
                "s/<commit_order> reverse limit 1",
                "metadata/object current indexes",
            ],
            writes: &[],
            indexes: &["s", "m", "n", "o", "k"],
            transaction_boundary: "read-only catalog snapshot load",
            expected_row_counts: "one snapshot row plus bounded active object rows",
            maximum_mutation_size: "none",
        },
        OperationInventory {
            operation: CatalogOperation::CreateSchema,
            typed_call: "commit(CreateSchema)",
            reads: &["schema name fence", "latest snapshot"],
            writes: &[
                "schema object row",
                "name lookup",
                "snapshot row",
                "changes row",
            ],
            indexes: &["o", "n", "s", "c", "w"],
            transaction_boundary: "single metadata commit",
            expected_row_counts: "one schema row and one name row",
            maximum_mutation_size: "bounded by object row and index fanout",
        },
        OperationInventory {
            operation: CatalogOperation::CreateTable,
            typed_call: "commit(CreateTable)",
            reads: &["schema fence", "table name lookup", "latest snapshot"],
            writes: &[
                "table object row",
                "column rows",
                "name lookup",
                "snapshot changes",
            ],
            indexes: &["o", "k", "n", "s", "c", "C", "w"],
            transaction_boundary: "single metadata commit",
            expected_row_counts: "one table row plus one row per column",
            maximum_mutation_size: "bounded by column count",
        },
        OperationInventory {
            operation: CatalogOperation::AppendDataFiles,
            typed_call: "commit(AppendFiles)",
            reads: &["latest snapshot", "table schema fence"],
            writes: &[
                "data file rows",
                "current file index",
                "begin timeline",
                "changes",
            ],
            indexes: &["d", "D", "b", "s", "c", "C", "w"],
            transaction_boundary: "single append commit until preflight budget is exceeded",
            expected_row_counts: "one data-file row and two file indexes per appended file",
            maximum_mutation_size: "preflight encoded bytes below FDB safety budget",
        },
        OperationInventory {
            operation: CatalogOperation::CurrentTableScan,
            typed_call: "list_files(current)",
            reads: &["D/<table_id>", "d/<data_file_id>", "X/<data_file_id>"],
            writes: &[],
            indexes: &["D", "d", "X"],
            transaction_boundary: "paginated read",
            expected_row_counts: "one current index row per active file",
            maximum_mutation_size: "none",
        },
        OperationInventory {
            operation: CatalogOperation::FilePruning,
            typed_call: "list_files(current_or_snapshot, pruning)",
            reads: &[
                "F/<table_id>/<column_id>",
                "f/<data_file_id>/<column_id>",
                "q",
                "b begin timeline for historical unpartitioned files",
            ],
            writes: &[],
            indexes: &["F", "f", "q", "b"],
            transaction_boundary: "paginated read with batched stats lookup",
            expected_row_counts: "one stats row per requested file and predicate column",
            maximum_mutation_size: "none",
        },
        OperationInventory {
            operation: CatalogOperation::TimeTravelScan,
            typed_call: "list_files(snapshot_order)",
            reads: &["S timestamp index", "b begin timeline", "y delete timeline"],
            writes: &[],
            indexes: &["S", "b", "e", "y"],
            transaction_boundary: "paginated historical read",
            expected_row_counts: "bounded timeline rows for the table page",
            maximum_mutation_size: "none",
        },
        OperationInventory {
            operation: CatalogOperation::UpdateOrDelete,
            typed_call: "commit(DeleteFiles)",
            reads: &["latest snapshot", "table data fence", "data file rows"],
            writes: &[
                "delete rows",
                "current delete pointers",
                "end timeline",
                "changes",
            ],
            indexes: &["x", "X", "y", "e", "E", "s", "c", "C", "w"],
            transaction_boundary: "single delete commit until preflight budget is exceeded",
            expected_row_counts: "one delete row plus one timeline row per affected file",
            maximum_mutation_size: "bounded by file/delete fanout",
        },
        OperationInventory {
            operation: CatalogOperation::AlterTable,
            typed_call: "commit(AddColumns/RenameColumns/DropColumns/ChangeColumnTypes/ChangeColumnDefaults/ChangePartitionKeys/ChangeSortKeys/ChangeComments)",
            reads: &[
                "schema/table fences",
                "current table object",
                "column-created-with-table lookup",
            ],
            writes: &[
                "new table/column versions",
                "old end_order rows",
                "schema versions",
            ],
            indexes: &["o", "k", "g", "E", "s", "c", "C", "w"],
            transaction_boundary: "single DDL commit",
            expected_row_counts: "one new version row per changed object",
            maximum_mutation_size: "bounded by altered column count",
        },
        OperationInventory {
            operation: CatalogOperation::Compaction,
            typed_call: "commit(RewriteFiles)",
            reads: &["table data fence", "current files"],
            writes: &["replacement files", "old end_order rows", "cleanup indexes"],
            indexes: &["d", "D", "b", "e", "E", "s", "c", "C", "w"],
            transaction_boundary: "single rewrite commit or future staged manifest",
            expected_row_counts: "replacement file rows plus end-order rows for old files",
            maximum_mutation_size: "preflight; likely benchmark-gated for staging",
        },
        OperationInventory {
            operation: CatalogOperation::DataInlining,
            typed_call: "commit(InlineRows)",
            reads: &["table inline registry", "latest snapshot"],
            writes: &["inline table rows", "inline deletions", "changes"],
            indexes: &["i", "I", "s", "c", "C", "E"],
            transaction_boundary: "single commit for payloads at or below 100 KB",
            expected_row_counts: "one inline manifest and bounded inline chunks",
            maximum_mutation_size: "100 KB logical payload ceiling before encoding",
        },
        OperationInventory {
            operation: CatalogOperation::ChangeDataFeed,
            typed_call: "list_changes",
            reads: &["C/<table_id>/<commit_order>", "c/<commit_order> fallback"],
            writes: &[],
            indexes: &["C", "c"],
            transaction_boundary: "paginated read",
            expected_row_counts: "one table-scoped change row per committed table change",
            maximum_mutation_size: "none",
        },
        OperationInventory {
            operation: CatalogOperation::SnapshotMaintenance,
            typed_call: "maintenance(ListSnapshots/DeleteSnapshots)",
            reads: &[
                "s/<commit_order>",
                "S/<commit_timestamp>/<commit_order>",
                "E cleanup indexes",
            ],
            writes: &["snapshot expiry markers", "cleanup eligibility rows"],
            indexes: &["s", "S", "E"],
            transaction_boundary: "maintenance stage; paginated and checkpointable",
            expected_row_counts: "one row per snapshot page plus bounded cleanup rows",
            maximum_mutation_size: "benchmark-gated before enabling deletes",
        },
        OperationInventory {
            operation: CatalogOperation::CleanupFiles,
            typed_call: "maintenance(CleanupFiles)",
            reads: &["E cleanup indexes", "scheduled physical file rows"],
            writes: &["remove cleanup schedule rows after external deletion"],
            indexes: &["E"],
            transaction_boundary: "maintenance stage; checkpointed batches",
            expected_row_counts: "bounded cleanup page",
            maximum_mutation_size: "bounded cleanup batch below FDB safety budget",
        },
        OperationInventory {
            operation: CatalogOperation::ConfigOptions,
            typed_call: "commit(SetConfigOption)",
            reads: &["metadata setting scope"],
            writes: &[
                "metadata setting row",
                "snapshot changes when transactional",
            ],
            indexes: &["m", "s", "c"],
            transaction_boundary: "single metadata commit",
            expected_row_counts: "one setting row per scope/key",
            maximum_mutation_size: "bounded by option value size",
        },
        OperationInventory {
            operation: CatalogOperation::MetadataInspection,
            typed_call: "inspect(GetTableSizes/GetAllSnapshots)",
            reads: &[
                "table-scoped current file indexes",
                "snapshot indexes",
                "metadata object rows",
            ],
            writes: &[],
            indexes: &["D", "s", "S", "o"],
            transaction_boundary: "read-only paginated inspection",
            expected_row_counts: "bounded inspection rows for requested table or snapshot page",
            maximum_mutation_size: "none",
        },
        OperationInventory {
            operation: CatalogOperation::Migration,
            typed_call: "unsupported(Migration)",
            reads: &["SQL-backed DuckLake metadata version rows"],
            writes: &["none in V1 KV backend"],
            indexes: &[],
            transaction_boundary: "explicitly unsupported for V1 no-upgrade non-goal",
            expected_row_counts: "none",
            maximum_mutation_size: "none",
        },
    ]
}

#[must_use]
pub const fn risk_inventory() -> &'static [RiskInventory] {
    &[
        RiskInventory {
            name: "latest snapshot lookup",
            mitigation: "reverse scan s/<commit_order> with limit 1",
            need: ReleaseReadinessNeed::RequiredBeforeFdbProof,
            fixture_owner: "given_empty_catalog_when_initialized_then_latest_snapshot_is_read_by_reverse_scan",
        },
        RiskInventory {
            name: "snapshot by timestamp",
            mitigation: "S/<commit_timestamp>/<commit_order> reverse lookup",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "timestamp_snapshot_resolution_fixture",
        },
        RiskInventory {
            name: "catalog open on large catalogs",
            mitigation: "current object/name indexes first; paginate historical object scans",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "catalog_open_uses_current_indexes",
        },
        RiskInventory {
            name: "current file listing",
            mitigation: "D/<table_id>/<data_file_id> current index with pagination",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "current_file_listing_uses_table_scoped_index",
        },
        RiskInventory {
            name: "delete-file attachment",
            mitigation: "X/<data_file_id> current pointer before historical delete timeline scans",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "current_scan_attaches_delete_files_without_n_plus_one",
        },
        RiskInventory {
            name: "file stats pruning",
            mitigation: "batch F/<table_id>/<column_id>/<data_file_id> before interval indexes",
            need: ReleaseReadinessNeed::BenchmarkGatedDeferred,
            fixture_owner: "stats_pruning_benchmark_fixture",
        },
        RiskInventory {
            name: "partition pruning",
            mitigation: "q partition lookup with snapshot visibility filtering; dedicated historical timeline is benchmark-gated",
            need: ReleaseReadinessNeed::BenchmarkGatedDeferred,
            fixture_owner: "partition_pruning_benchmark_fixture",
        },
        RiskInventory {
            name: "change data feed",
            mitigation: "C/<table_id>/<commit_order> table-scoped change rows",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "change_feed_does_not_scan_unrelated_global_commits",
        },
        RiskInventory {
            name: "conflict resolution after stale base",
            mitigation: "table/object-scoped change keys with typed base-too-stale errors",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "stale_base_conflict_window_is_capped",
        },
        RiskInventory {
            name: "expire snapshots and cleanup",
            mitigation: "E/<table_id>/<end_order>/<object_kind>/<object_id> cleanup indexes",
            need: ReleaseReadinessNeed::BenchmarkGatedDeferred,
            fixture_owner: "cleanup_is_range_bounded_by_table_and_order",
        },
        RiskInventory {
            name: "data inlining",
            mitigation: "100 KB logical payload ceiling and chunk count preflight",
            need: ReleaseReadinessNeed::BenchmarkGatedDeferred,
            fixture_owner: "inline_payload_rejects_oversized_rows",
        },
        RiskInventory {
            name: "large append commits",
            mitigation: "preflight mutation count and encoded bytes before publication",
            need: ReleaseReadinessNeed::RequiredBeforeDuckLakeSmoke,
            fixture_owner: "large_append_rejected_before_publish",
        },
        RiskInventory {
            name: "debug/export queries",
            mitigation: "typed operations remain serving path; export stays paginated best-effort",
            need: ReleaseReadinessNeed::BenchmarkGatedDeferred,
            fixture_owner: "debug_export_cannot_serve_catalog_reads",
        },
    ]
}
